### ISSUE TITLE
E/configParser - ReferenceError: WARN is not defined

### ISSUE THREAD

**Issue by pitzqa** [igniteram/protractor-cli#28]
Hello,
I faced Same issue "E/configParser - ReferenceError: WARN is not defined" while running my protractor.conf.js file in protractor cli.

protractor.conf.js file,

const HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');

exports.config = {
allScriptsTimeout: 120000,
seleniumAddress: 'http://localhost:4444/wd/hub',
baseUrl: 'https://*/login',
capabilities: {
browserName: 'chrome'
},
framework: 'jasmine',
specs: [
'/home/kl/Desktop/EV/ev-ng/e2e'
],
logLevel: WARN,
beforeLaunch: () => {
require('ts-node').register({
project: './tsconfig.e2e.json'
});
},
jasmineNodeOpts: {
defaultTimeoutInterval: 120000,
showColors: true,
random: false,
},
onPrepare: () => {
jasmine.getEnv().addReporter(new HtmlScreenshotReporter({
dest: 'target/screenshots',
filename: 'protractor_jasmine_report.html'
}));
},
};

![example 1](https://user-images.githubusercontent.com/39620464/41354081-b1106d78-6f3b-11e8-9490-8951cf01d821.png)

**Comment by igniteram** [comment]
@pitzqa Yes, I caught this small issue while unit testing. I have already raised a PR https://github.com/igniteram/protractor-cli/pull/27 which would fix this.

Meanwhile you can just put the `WARN` in string qoutes --> `'WARN'` in `protractor.conf.js` file

**Comment by pitzqa** [comment]
@igniteram Its working. Thank You so much.

**Comment by igniteram** [comment]
fixed this issue with https://github.com/igniteram/protractor-cli/pull/27, please download the latest `protractor-cli` to see the changes. Closing this issue!
